### PR TITLE
feat: Adds test to create zip using reflection

### PR DESCRIPTION
**Pull request by lfvbarcus**
This PR adds a test to make sure that the logic to create a .zip file works as expected. Since the method and the properties required are private, I have relied on reflection in order to test the code.

### CODE REVIEW

**Review by lfvjimisola — COMMENTED** [review]
Are the resources taken from reqstool-demo?

I was thinking that we want minimize the work of maintaining these files as much as possible.

**Comment by lfvbarcus** [comment]
> Are the resources taken from reqstool-demo?
> 
> I was thinking that we want minimize the work of maintaining these files as much as possible.

Yes, the resources are taken from reqstool-demo, but could essentialy be just empty files as we are not really interested in the content of the files. I can replace the content if you prefer.

**Comment by lfvjimisola** [comment]
> > Are the resources taken from reqstool-demo?
> > I was thinking that we want minimize the work of maintaining these files as much as possible.
> 
> Yes, the resources are taken from reqstool-demo, but could essentialy be just empty files as we are not really interested in the content of the files. I can replace the content if you prefer.

You decide.

**Comment by lfvbarcus** [comment]
> > > Are the resources taken from reqstool-demo?
> > > I was thinking that we want minimize the work of maintaining these files as much as possible.
> > 
> > 
> > Yes, the resources are taken from reqstool-demo, but could essentialy be just empty files as we are not really interested in the content of the files. I can replace the content if you prefer.
> 
> You decide.

I decided to just use dummy files, as the new test is not concerned about file content in order to produce the zip.

**Review by lfvjimisola — APPROVED** [review]

**Pull request merged**
